sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- '8'
cache:
  yarn: true
branches:
  except:
  - stable
before_install:
- export START_TIME=$( date +%s )
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm i -g yarn
install:
- yarn add @ckeditor/ckeditor5-dev-tests
- ckeditor5-dev-tests-install-dependencies
script:
- ckeditor5-dev-tests-travis
after_success:
- ckeditor5-dev-tests-save-revision
after_script:
- export END_TIME=$( date +%s )
- ckeditor5-dev-tests-notify-travis-status
env:
  global:
  - secure: JESDEdWvCivJgsOM9AYn5IGudJKItJKqRqWpHVXZI4/pAf2wr81Dlx/y4NJkHHurcoarCnJtX03MY1rXlqjKROGUKy4YzQYDQaE0FkCz20xOXVgglb9GfZVTH/hTs/RnVuf/iTwK+Vg/X5xeI8zNR2XPd2sD5V8wuK87w5h0OunMz8Hdrc4UrS1UvY+5+vYc79E2/GqbGQMHvO6EZpTvg6Tpx5Ndw7gGn4N26Bok+HdbH32SwadKE7fk/HQpmsHoNkKCawp99VdtLR8HaA3MOY89Iq/SNaGtdGFGvsG5hUpbDQCfrPol91U/dIWDK1sFcwp4lrAFcYjc6AKoL/lxIy43esyO/2VqUrEM+vMdM60iif8HMoqMtf/V4LuKHTju4YyxF8UgGD5Ldg2b8wwFxwgLVmHFKpxja0hlbXWdoWFMwkLeXgow+1MxrMO+UbbBmAubjZft2y+DV/2a5UXF8U2ZU64p1IcBxBVW8OQ3WnAqosl+ye0VvmmhghYmKwh2sip1izAG6PGaF1N80fvKIjir+k9lG7bmK+T0K6VH6xQ31NNDy5WjY0g9EOZTChf4SeOD938gKxigey13kRSaMOPzxNjnPKcU+d84WTpvpvgxIdsibgLxFxsUmOXJwCa/b8x1g6y00RhA49szTWoD3JQ8r+Pbte9M795wjPdaZDo=
  - secure: Fa7KGX1VnF3kdEv159/VzJTzx0NMytO8RfJ28V+MSR3pJN3Hry5V3j08HxaGviwfqHnRUb+tBxQdXjIqRyolMEf8182u/cBwugaXPXH0g/IzOZvJZkSEzheQ/h0TtnxR+qsFylLmzrBtO6mjAY4xwo/uYZYMM2STToDMBiRGThM/Id6QTmNKRbk4koUTSadqIkbaVJDTIsaoRRshClmkjYM6XQSxWDAEo1lPfP1izhbscFSHb9VxWbd7wkwv6PJh4N2FocO5XOHlQG2bICMvfHzS1SPve/iRhG/umW1xiEpAphPd+1mtB3iZGVjXvLGxFOwkS/iAtIejq34ERH3h+ZRE1Ix6avxyyJjcSQmuRaKc4DwLAMNm4LYKxNwBfuBF9uZKFchSfnCt12epzD1yABr6tmBri9iSlColEwAPWQ8I3Sb4lyAGa8wSCBg6pxCHvX083XA6CfDXuMdqxwWQKYeAzb6NEYnSs4t5WXLThoEHcVd/jfGaMg/tLe1wixPf1Zdxg5OFCUYq7Mr3gEfgUNk728yJ06H8spX9pLOjWYdccNTAlLWlrRG4m4Dsuualokd6/nV/7tg0ggKgOwrNPyTmPtkd/drA2TxtfAwV1wfvoALxW3JxqYZt6l1RLaZsRbckEdsV5neX3oTh8jdvu2xvuSNLgaYLcnprSH7Fa0c=
  - secure: vIo41xdq7q/SvWgrgEULKOhc8+Tk2NVUT1E0a6Mab+X2HJlgj6y5gBp4j/tzV3X8mpYBFhCcFY7P89hbSgp4k1RKV3B2YWRoMJIEFp8z++7G49qmTzWAygoSH8+9xW7C1MTioSsJapYGiRp+5u2D07mjZg20I4m4KHq88czS6NvAl96PhQOQvx0p5aXh4zKPvr+DEjj5HKew0SQ09f4neF8vpabgoN/BaZ5d9V2vLWwMJ1wWz923zwT5AkFt57s4cjvN1py7xfpPRc3vTx7KL0s8wVMEZnAFfdwsZqKbJQotHDrHvEbmgs/crk1e6NP1T/lK3D8dR0i2ZCCaNHx1HJjz0U81JV6lkr0b+ITLtNmABeAXC0XlM2AOqXmr6OzqyBRYcok97E1nXsyRwb54Q03cNa89AldUcnpQFm9DPgmOD5By2+XONUYK//r0IuZsZcdJ+FkglWyy0q96UhiUd+NLOeQO+kYVyaEVowydMRt4wi0UknVrQ2o2AadLfAEFgsFkGqTRVtg4vhdpK5+H4JXT2vemavN/Y6iTbuwb3OOp1kIoR7r5PVVAXZQRJ7nl7juGqaWSVfGUE1CwT7A1ep/A+8fZZU15icKoTHFtbtsE1bywuhkSay3fo/ixBO+vTEK9OVoJ82g7CckT0YI6ef6i9CHS1/nJ6qkJuGt55xE=
